# Using the database Data11tumors.csv for Cancer Classification based on Microarray Gene Expression:
(a) Apply Exploratory Data Analysis.
(b) Apply the Machine Learning algorithm Gaussian Naïve Bayes and evaluate
the performance without and with parameters optimization, discuss the results obtained 

In [73]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns

# (a) Exploratory Data Analysis


In [47]:

df = pd.read_csv("Data11tumors.csv")
#To see first 10 rows of the dataset
df.head(10)

Classes  Gen1  Gen2  Gen3  Gen4  Gen5  Gen6  Gen7  Gen8  Gen9  ...  \
0        7   153   228    32    30   -36    48   984   -19   537  ...   
1        7   154    99    43    55    66    63  5051   -26  1001  ...   
2        7    84    85    19    28  -104    28  2387   -80  1131  ...   
3        7   234   169    40    36    81     6  2657    -6  1214  ...   
4        7   104    58    42    13   107     5  3562    18  1464  ...   
5        7   207   408    56     6    41    33  2617    40  1243  ...   
6        7   188   245    45    18   -15    44  1885    25  1313  ...   
7        7   221   132    84    19    81    74  2589   -21   742  ...   
8        7   198   328    13    41    16    38  2536   -35  1006  ...   
9        7   303   261    53    71   -40    66  1184   -28   711  ...   

   Gen12524  Gen12525  Gen12526  Gen12527  Gen12528  Gen12529  Gen12530  \
0       100        30        83        28        57       106       128   
1        27        43        90        30        82       485       896   
2       -32        51       110        10        86        62        76   
3        43        52        82        12       135        60        69   
4       159        42        73         1        82        60        50   
5        71        71       131        11       146       204       183   
6        22        48        90        14       113        76       131   
7        16        36       182       -35        98       213       198   
8        26        19        90        42       122        27       103   
9        49        44        58         7       -25       106       154   

   Gen12531  Gen12532  Gen12533  
0         5        74      -188  
1        -2        91       -78  
2       -47        92      -103  
3        22        89      -180  
4        30        74      -198  
5        -2       146      -152  
6         4        98       -98  
7        -5       184      -198  
8         8        75       105  
9        12       131      -224  

[10 rows x 12534 columns]

In [35]:
df.tail(10)

Classes  Gen1  Gen2  Gen3  Gen4  Gen5  Gen6  Gen7  Gen8  Gen9  ...  \
164        0   195   432    20    51     1   -66   513   -29  1660  ...   
165        0   197  1340    39    64  -186   -86   -40     6  2280  ...   
166        0   158   542    76    70    -4    40   110   -17  1943  ...   
167        0   106   391    44   104   -52  -104   -10   -93  1573  ...   
168        0   105   415    65    61    -7   -49   -80   -76  1757  ...   
169        0   157   578    40    58     5   -49    57   -29  3306  ...   
170        0   286   882   110   -19  -142   -66    -5    23  2701  ...   
171        0   579   667    55   -41   -98  -138  -164   -61  2812  ...   
172        0   252   582    88     3    44  -162   553  -150  2020  ...   
173        0    83   420    14    84    12     1   153   -38  1833  ...   

     Gen12524  Gen12525  Gen12526  Gen12527  Gen12528  Gen12529  Gen12530  \
164        67        69        66        24       132        79       145   
165       -24       102        24        72       480       113       319   
166       -29        43        84        57       160        55        74   
167       -47        67        59        68       275       234       337   
168       -83        57       121        40       162       134       201   
169         4        45        64        37       169        91       180   
170       -91       130       137       -61        75        36        58   
171      -110       107       199       -60        59         8        77   
172       -66        92       -26       -44       148        43        73   
173        -5        85        96        92        67        32        30   

     Gen12531  Gen12532  Gen12533  
164        17        63      -149  
165        45       139      -174  
166        -2        96      -179  
167         7       139      -195  
168        18       114      -256  
169        -4        60      -142  
170        44       161      -433  
171       -42       171      -371  
172         0       201      -333  
173        12        80      -180  

[10 rows x 12534 columns]

In [4]:

print(df.shape)

(174, 12534)


In [5]:
#To know the data types of the variables.
df.dtypes

Classes     int64
Gen1        int64
Gen2        int64
Gen3        int64
Gen4        int64
            ...  
Gen12529    int64
Gen12530    int64
Gen12531    int64
Gen12532    int64
Gen12533    int64
Length: 12534, dtype: object

In [36]:
df.describe().T

count        mean         std    min     25%    50%     75%     max
Classes   174.0    4.425287    3.245743    0.0    2.00    4.0    7.00    10.0
Gen1      174.0  218.413793  117.290761 -122.0  148.75  210.5  281.75   616.0
Gen2      174.0  537.942529  268.926376   30.0  360.00  520.5  706.75  1419.0
Gen3      174.0   71.965517   43.827156  -24.0   44.00   65.0   87.75   247.0
Gen4      174.0   83.706897  122.828468  -80.0   24.25   65.0  111.00  1307.0
...         ...         ...         ...    ...     ...    ...     ...     ...
Gen12529  174.0   62.850575   80.848968 -184.0   16.00   43.0   96.75   485.0
Gen12530  174.0  102.396552  127.692587  -75.0   20.50   73.5  145.00   896.0
Gen12531  174.0   12.913793   27.441552  -56.0   -4.00   10.0   25.50   109.0
Gen12532  174.0  206.942529  402.505214   37.0   96.00  142.0  210.50  4888.0
Gen12533  174.0 -220.873563  217.480811 -992.0 -332.50 -208.5 -142.00  1351.0

[12534 rows x 8 columns]

In [38]:
df.Classes.unique()

array([ 7,  1,  2,  3,  4,  5,  6,  0,  8,  9, 10])

In [9]:
df.isnull().sum()

Classes     0
Gen1        0
Gen2        0
Gen3        0
Gen4        0
           ..
Gen12529    0
Gen12530    0
Gen12531    0
Gen12532    0
Gen12533    0
Length: 12534, dtype: int64

In [13]:

#To know the count of each class:
df['Classes'].value_counts()

0     27
7     26
2     26
3     23
9     14
10    14
4     12
5     11
1      8
6      7
8      6
Name: Classes, dtype: int64

In [45]:
df.corr()

Classes      Gen1      Gen2      Gen3      Gen4      Gen5  \
Classes   1.000000 -0.122906 -0.386454 -0.104327  0.065546  0.009746   
Gen1     -0.122906  1.000000  0.335859  0.241444 -0.123989 -0.301285   
Gen2     -0.386454  0.335859  1.000000  0.244218 -0.117454 -0.229678   
Gen3     -0.104327  0.241444  0.244218  1.000000 -0.012979 -0.150880   
Gen4      0.065546 -0.123989 -0.117454 -0.012979  1.000000  0.005021   
...            ...       ...       ...       ...       ...       ...   
Gen12529  0.028483 -0.234791 -0.325180  0.143218 -0.077945  0.180772   
Gen12530 -0.014970 -0.127079 -0.192264  0.264731 -0.132470  0.135209   
Gen12531 -0.235101  0.220235  0.224995  0.224216 -0.015869 -0.196089   
Gen12532 -0.043766  0.000891  0.055826  0.096255  0.011146 -0.031366   
Gen12533  0.185227 -0.330172 -0.334725 -0.139686  0.474120  0.173755   

              Gen6      Gen7      Gen8      Gen9  ...  Gen12524  Gen12525  \
Classes   0.334543  0.197947  0.042604 -0.212305  ...  0.194956 -0.161912   
Gen1     -0.066934 -0.176200 -0.030922  0.001206  ... -0.174236  0.412143   
Gen2     -0.249078 -0.304167  0.024746  0.257993  ... -0.186326  0.415163   
Gen3     -0.142334  0.092944 -0.032574 -0.247088  ... -0.345071  0.455954   
Gen4      0.173236  0.016677  0.014081 -0.211205  ... -0.103634  0.016873   
...            ...       ...       ...       ...  ...       ...       ...   
Gen12529  0.001035  0.537850  0.017481 -0.099250  ...  0.036985 -0.093454   
Gen12530 -0.016761  0.503523  0.004927 -0.103299  ...  0.043828  0.008862   
Gen12531 -0.135209 -0.163106  0.074650  0.018540  ...  0.115315  0.189387   
Gen12532 -0.053809 -0.116434 -0.022671 -0.062887  ...  0.119377  0.173089   
Gen12533  0.193614  0.241454  0.007801 -0.146877  ...  0.301672 -0.325014   

          Gen12526  Gen12527  Gen12528  Gen12529  Gen12530  Gen12531  \
Classes  -0.039217  0.025130 -0.032838  0.028483 -0.014970 -0.235101   
Gen1      0.193058 -0.152631 -0.338063 -0.234791 -0.127079  0.220235   
Gen2      0.129953 -0.053406 -0.115217 -0.325180 -0.192264  0.224995   
Gen3      0.335723 -0.186256 -0.184106  0.143218  0.264731  0.224216   
Gen4      0.184160 -0.089724 -0.065803 -0.077945 -0.132470 -0.015869   
...            ...       ...       ...       ...       ...       ...   
Gen12529 -0.083641  0.084163  0.239728  1.000000  0.892126 -0.063254   
Gen12530 -0.064945  0.125646  0.280059  0.892126  1.000000  0.068186   
Gen12531  0.006501  0.068349  0.138431 -0.063254  0.068186  1.000000   
Gen12532  0.006315  0.052069  0.032978 -0.026238  0.029936  0.011982   
Gen12533 -0.131243  0.212051  0.306264  0.201818  0.219948 -0.017661   

          Gen12532  Gen12533  
Classes  -0.043766  0.185227  
Gen1      0.000891 -0.330172  
Gen2      0.055826 -0.334725  
Gen3      0.096255 -0.139686  
Gen4      0.011146  0.474120  
...            ...       ...  
Gen12529 -0.026238  0.201818  
Gen12530  0.029936  0.219948  
Gen12531  0.011982 -0.017661  
Gen12532  1.000000  0.054586  
Gen12533  0.054586  1.000000  

[12534 rows x 12534 columns]

It's showing that the corelation is very low

In [14]:
#Separating independant variable and dependent variable("Classes")
X = df.drop(['Classes'], axis=1)
y = df['Classes']
# print(X.head())
print(X.shape)
# print(y.head())
print(y.shape)

(174, 12533)
(174,)


In [19]:
# Splitting the dataset to Train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 100)

#to know the shape of the train and test dataset.
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(121, 12533)
(121,)
(53, 12533)
(53,)


In [17]:
#Scaling X data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit(X_train).transform(X_train)
X_test_scaled = scaler.fit(X_test).transform(X_test)



# (B) Gaussian Naïve Bayes and performance evaluation without and with parameters optimization

In [68]:
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

GB = GaussianNB()
GB.fit(X_train, y_train)
predictions = GB.predict(X_test)

print(predictions)


[ 7  3  1  4 10  2  7  9  4  2  2  7  7  2 10  9  2  0  8  9  3  5  3 10
  2  2  7  0  3  0  0  0  3  4  0  2  2  3  2  7  3 10  2  3  7  7  6  0
  3  2  0  3  7]


In [25]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))

0.8679245283018868


Here we can see that the accuracy is .86

In [34]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))



[[8 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0 0]
 [0 0 9 0 0 0 0 0 0 0 0]
 [0 0 0 8 0 0 0 0 0 0 0]
 [0 0 0 1 2 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 9 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 2 0]
 [0 0 1 0 0 0 0 0 0 1 4]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.25      0.40         4
           2       0.75      1.00      0.86         9
           3       0.80      1.00      0.89         8
           4       0.67      0.67      0.67         3
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         9
           8       1.00      1.00      1.00         1
           9       0.67      0.67      0.67         3
          10       1.00      0.67      0.80         6

    accuracy                           0.87        53
   macro avg       0

In [ ]:
Here we can see that the accuracy is .87

In [72]:
from sklearn.naive_bayes import BernoulliNB
BNG = BernoulliNB()
BNG.fit(X_train, y_train)
print(accuracy_score(y_test, predictions))


0.8679245283018868


# Parameter Optimization

In [58]:
param_grid_nb = {
    'var_smoothing': np.logspace(0,-9, num=100)
}

In [64]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
nbModel_grid = GridSearchCV(estimator=GaussianNB(), param_grid=param_grid_nb, verbose=1, cv=4, n_jobs=-1)
nbModel_grid.fit(X_train, y_train)
print(nbModel_grid.best_estimator_)

#Fitting 10 folds for each of 100 candidates, totalling 1000 fits
GaussianNB(priors=None, var_smoothing=1.0)

Fitting 4 folds for each of 100 candidates, totalling 400 fits
GaussianNB(var_smoothing=0.0023101297000831605)


GaussianNB(var_smoothing=1.0)

In [65]:
y_pred = nbModel_grid.predict(X_test)
print(y_pred)

[ 7  3  1  1 10  2  7  9  4  9  2  7  7  0 10 10  2  0  8  9  3  5  3 10
  2  2  7  0  3  0  0  0  3  4  0  0  2  3 10  7  3 10 10  8  7  7  6  0
  4  2  0  3  7]


In [66]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred), ": is the confusion matrix")
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred), ": is the accuracy score")

[[8 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 1 0 1]
 [1 0 7 0 0 0 0 0 0 0 1]
 [0 0 0 8 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 9 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 3 0]
 [1 0 0 0 0 0 0 0 0 0 5]] : is the confusion matrix
0.9056603773584906 : is the accuracy score


Here we can see that the accuracy score has been increased by .90 by optimization.